### ISSUE TITLE
Toggle able tracking in wilderness

### ISSUE THREAD

**Issue by W1GZY** [TiboDeMunck/runelite-live-friend-locations-api#1]
Really like the plugin and I really like idea!
I was wondering if it was possible to add a slider for turning the tracking on/off for wilderness automatically so we dont have to toggle the plugin off manually for doing things in the wilderness.

**Comment by TiboDeMunck** [comment]
When I first read your request I was a big fan of the idea. However, different plugins with the same request had a very interesting standpoint on this. I will refer you to the other post: https://github.com/runelite/runelite/pull/14468#issuecomment-993881791 . As of now, there doesn't seem to be an easy way to detect if a player is in the wilderness. I will do some more research on this and might reconsider depending on the possibilities.

**Comment by W1GZY** [comment]
I see where you are coming from and I totally understand the hassle of making this work compared to just disabling the plugin.

About the concern for safe zones, I was thinking more of the whole wilderness (and wilderness dungeons) as one big square and  not caring about the safe zones inside the wilderness. I was thinking more like if they cross this square they just dissapear in the map or something similar.

I dont know if this is too much work or if it is possible at all and I appreciate that you are looking into it. It is mostly for my IM and HCIM friends that doesnt want to be a part of this brilliant plugin because they might forget to turn it off while doing risky stuff. 

Thanks for the quick reply

**Comment by TiboDeMunck** [comment]
Filters have been added, waiting for runelite admins to merge update with master.

On further issues regarding the plugin, please refrain from using the API's repository, use the plugins repository: https://github.com/TiboDeMunck/runelite-live-friend-locations-plugin
