### ISSUE TITLE
Heroku servers aren't connecting to the github, any work around?

### ISSUE THREAD

**Issue by FranciisM** [TiboDeMunck/runelite-live-friend-locations-api#3]

**Comment by TiboDeMunck** [comment]
I have transferred the issue to this repository as it is an issue with the API and not with the plugin.

- Have you followed the instructions in the ReadMe file of this repository? 
- Could you please elaborate what you mean by "servers aren't connecting"?

**Comment by FranciisM** [comment]
Hey, thanks for getting back to me so soon.

I am following the ReadMe file on the repository and have got as far as
step 3, where I am struggling to deploy the file with my GitHub account,
when I click 'connect to github' it says 'Item could not be retrieved:
Internal Server Error'. I'm not very advanced with github so if you could
help me fix this that'd be great. I am also unsure if the error is coming
from the github account i'm connecting with or if it is just the Heroku
servers.

Thanks,
Francis.

**Comment by TiboDeMunck** [comment]
Seems to be a temporary issue: https://status.heroku.com/incidents/2413
Easiest "work around" is: https://devcenter.heroku.com/articles/git

**Comment by FranciisM** [comment]
Ah yeah thanks for letting me know it is a temporary issue, I tried to
install Heroku CLI but it wasn't loading the app for some weird reason.
I'll wait till hopefully the Heroku servers are back.

Thanks for your help.
