### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by invasion32** [TiboDeMunck/runelite-live-friend-locations-api#4]
not a programmer of any kind. would love to get this running, cant figure out even with the read me. is there a video showing the setup that exists somewhere?

**Comment by TiboDeMunck** [comment]
Hey I'm on vacation at the moment so it is difficult to record a video and upload it. Is there anything specific you can't figure out that I can help with?

**Comment by TiboDeMunck** [comment]
https://www.youtube.com/embed/eMgULNYfU1k
