### ISSUE TITLE
Huge pixalated Clan icons

### ISSUE THREAD

**Issue by W1GZY** [TiboDeMunck/runelite-live-friend-locations-api#5]
Is there any way to reduce the size of the pixelated icons so it doesnt look this way? (Good idea btw, love the variety of icons in the map!)

![download](https://user-images.githubusercontent.com/96368352/178113727-fc5aba19-1461-483d-9d01-8f4d5225ada8.png)

![download](https://user-images.githubusercontent.com/96368352/178113711-b9a5b8d2-54ee-4e49-930f-b640cbc8ce57.png)

**Comment by W1GZY** [comment]
Was late to the game, Tibo already mentioned this issue in another issue.

**Comment by TiboDeMunck** [comment]
I have plans to make the icons resizable but am on vacation at the moment.

**Comment by TiboDeMunck** [comment]
To start off: 
1) It's a pixel game, the pixilation are just the normal icons
2) I have an update pending that will allow you to change the size of the icons through the config panel
